CREATE DATABASE PARKING_LOT;
USE PARKING_LOT;

CREATE TABLE USER (
	VEHICLE_NUM VARCHAR(20) PRIMARY KEY,
    PW VARCHAR(50),
	FIRST_REG_DATE DATE,
	EXP_DATE DATE,
	TOTAL_REG_DATE SMALLINT UNSIGNED,
	TOTAL_FEE SMALLINT UNSIGNED
);

CREATE TABLE ENTRY_EXIT_RECORD(
	VEHICLE_NUM VARCHAR(20),
	ENTRY_DATE DATE,
	EXIT_DATE DATE,
	FEE SMALLINT UNSIGNED,
	CLASSIFICATION TINYINT,
	PRIMARY KEY(VEHICLE_NUM, ENTRY_DATE)
);

DROP TABLE USER;
DROP TABLE ENTRY_EXIT_RECORD;
