CREATE DATABASE PARKING_LOT;
USE PARKING_LOT;

CREATE TABLE USER (
	VEHICLE_NUM VARCHAR(20) PRIMARY KEY,
    PW VARCHAR(50),
	FIRST_REG_DATE DATETIME,
	EXP_DATE DATETIME,
	TOTAL_FEE INT UNSIGNED DEFAULT 0
);

CREATE TABLE ENTRY_EXIT_RECORD(
	VEHICLE_NUM VARCHAR(20),
	ENTRY_DATE DATETIME,
	EXIT_DATE DATETIME,
	FEE SMALLINT UNSIGNED,
	CLASSIFICATION TINYINT,
	PRIMARY KEY(VEHICLE_NUM, ENTRY_DATE)
);

DROP TABLE USER;
DROP TABLE ENTRY_EXIT_RECORD;


INSERT INTO USER VALUES ("1445", '1234', NOW(), NOW()+1, 20000); 
UPDATE USER SET 
	EXP_DATE = date_add((SELECT EXP_DATE FROM (SELECT EXP_DATE FROM USER WHERE VEHICLE_NUM = "1234") AS A) , INTERVAL 1 DAY),
    TOTAL_FEE = (SELECT TOTAL_FEE FROM (SELECT TOTAL_FEE FROM USER WHERE VEHICLE_NUM = "1234") AS B) + 50000
    WHERE VEHICLE_NUM = "1234";
SELECT * FROM USER;
